import type {
  GeneratedFile,
  GeneratorOptions,
  PlatformGenerator,
} from "@dota-themes/generator-core";
import type { HeroPalette } from "@dota-themes/palettes";

function generateGhosttyConfig(palette: HeroPalette): string {
  const t = palette.terminal;
  const name = palette.metadata.title;

  return `# ${name} theme for Ghostty
# Generated by dota-themes
# ${palette.metadata.description}

background = ${t.background}
foreground = ${t.foreground}
cursor-color = ${t.cursor}
selection-background = ${t.selectionBackground}
selection-foreground = ${t.foreground}

# Normal colors
palette = 0=${t.black}
palette = 1=${t.red}
palette = 2=${t.green}
palette = 3=${t.yellow}
palette = 4=${t.blue}
palette = 5=${t.magenta}
palette = 6=${t.cyan}
palette = 7=${t.white}

# Bright colors
palette = 8=${t.brightBlack}
palette = 9=${t.brightRed}
palette = 10=${t.brightGreen}
palette = 11=${t.brightYellow}
palette = 12=${t.brightBlue}
palette = 13=${t.brightMagenta}
palette = 14=${t.brightCyan}
palette = 15=${t.brightWhite}
`;
}

export const ghosttyGenerator: PlatformGenerator = {
  name: "ghostty",
  fileExtension: "conf",

  generate(options: GeneratorOptions): GeneratedFile[] {
    const content = generateGhosttyConfig(options.hero);
    const fileName = `dota-${options.hero.hero}`;
    return [{ path: `${options.outputDir}/${fileName}`, content }];
  },
};
