import type {
  GeneratedFile,
  GeneratorOptions,
  PlatformGenerator,
} from "@dota-themes/generator-core";
import { darken } from "@dota-themes/generator-core";
import type { HeroPalette } from "@dota-themes/palettes";

function generateZedTheme(palette: HeroPalette): string {
  const e = palette.editor;
  const c = palette.colors;
  const name = palette.metadata.title;

  const lines: string[] = [
    "{",
    `  "$schema": "https://zed.dev/schema/themes/v0.2.0.json",`,
    `  "name": "Dota ${name}",`,
    `  "author": "dota-themes",`,
    `  "themes": [`,
    "    {",
    `      "name": "Dota ${name}",`,
    `      "appearance": "dark",`,
    `      "style": {`,
    `        "background": "${e.background}",`,
    `        "border": "${darken(e.background, -0.08)}",`,
    `        "border.variant": "${darken(e.background, -0.06)}",`,
    `        "border.focused": "${c.primary}",`,
    `        "border.selected": "${c.primary}",`,
    `        "border.transparent": "transparent",`,
    `        "border.disabled": "${darken(e.background, -0.04)}",`,
    `        "elevated_surface.background": "${darken(e.background, 0.03)}",`,
    `        "surface.background": "${e.background}",`,
    `        "element.background": "${darken(e.background, 0.05)}",`,
    `        "element.hover": "${darken(e.background, 0.08)}",`,
    `        "element.active": "${darken(e.background, 0.12)}",`,
    `        "element.selected": "${e.selection}",`,
    `        "element.disabled": "${darken(e.background, 0.05)}",`,
    `        "ghost_element.background": "transparent",`,
    `        "ghost_element.hover": "${darken(e.background, 0.05)}",`,
    `        "ghost_element.active": "${darken(e.background, 0.08)}",`,
    `        "ghost_element.selected": "${e.selection}",`,
    `        "ghost_element.disabled": "transparent",`,
    `        "text": "${e.foreground}",`,
    `        "text.muted": "${e.comment}",`,
    `        "text.placeholder": "${darken(e.foreground, 0.25)}",`,
    `        "text.disabled": "${darken(e.foreground, 0.35)}",`,
    `        "text.accent": "${c.primary}",`,
    `        "icon": "${e.foreground}",`,
    `        "icon.muted": "${e.comment}",`,
    `        "icon.disabled": "${darken(e.foreground, 0.35)}",`,
    `        "icon.placeholder": "${darken(e.foreground, 0.25)}",`,
    `        "icon.accent": "${c.primary}",`,
    `        "status_bar.background": "${darken(e.background, 0.03)}",`,
    `        "title_bar.background": "${darken(e.background, 0.05)}",`,
    `        "toolbar.background": "${darken(e.background, 0.03)}",`,
    `        "tab_bar.background": "${darken(e.background, 0.05)}",`,
    `        "tab.inactive_background": "${darken(e.background, 0.03)}",`,
    `        "tab.active_background": "${e.background}",`,
    `        "tab.active_border": "${c.primary}",`,
    `        "tab.active_border_highlight": "${c.primary}",`,
    `        "tab.separator": "${darken(e.background, -0.06)}",`,
    `        "tab.bar.background": "${darken(e.background, 0.05)}",`,
    `        "editor.background": "${e.background}",`,
    `        "editor.gutter.background": "${e.gutter}",`,
    `        "editor.subheader.background": "${darken(e.background, 0.03)}",`,
    `        "editor.active_line.background": "${e.lineHighlight}",`,
    `        "editor.highlighted_line.background": "${darken(e.lineHighlight, 0.03)}",`,
    `        "editor.line_number": "${e.gutter}",`,
    `        "editor.active_line_number": "${e.cursor}",`,
    `        "editor.invisible": "${e.whitespace}",`,
    `        "editor.wrap_guide": "${darken(e.background, -0.04)}",`,
    `        "editor.active_wrap_guide": "${darken(e.background, -0.06)}",`,
    `        "editor.document_highlight.read_background": "${darken(e.selection, 0.5)}",`,
    `        "editor.document_highlight.write_background": "${e.selection}",`,
    `        "terminal.background": "${e.background}",`,
    `        "terminal.foreground": "${e.foreground}",`,
    `        "terminal.bright_foreground": "${e.foreground}",`,
    `        "terminal.dim_foreground": "${e.foreground}",`,
    `        "terminal.ansi.black": "${e.comment}",`,
    `        "terminal.ansi.bright_black": "${darken(e.foreground, 0.3)}",`,
    `        "terminal.ansi.dim_black": "${darken(e.foreground, 0.5)}",`,
    `        "terminal.ansi.red": "${c.error}",`,
    `        "terminal.ansi.bright_red": "${c.error}",`,
    `        "terminal.ansi.dim_red": "${darken(c.error, 0.3)}",`,
    `        "terminal.ansi.green": "${c.success}",`,
    `        "terminal.ansi.bright_green": "${c.success}",`,
    `        "terminal.ansi.dim_green": "${darken(c.success, 0.3)}",`,
    `        "terminal.ansi.yellow": "${c.warning}",`,
    `        "terminal.ansi.bright_yellow": "${c.warning}",`,
    `        "terminal.ansi.dim_yellow": "${darken(c.warning, 0.3)}",`,
    `        "terminal.ansi.blue": "${c.info}",`,
    `        "terminal.ansi.bright_blue": "${c.info}",`,
    `        "terminal.ansi.dim_blue": "${darken(c.info, 0.3)}",`,
    `        "terminal.ansi.magenta": "${c.secondary}",`,
    `        "terminal.ansi.bright_magenta": "${c.secondary}",`,
    `        "terminal.ansi.dim_magenta": "${darken(c.secondary, 0.3)}",`,
    `        "terminal.ansi.cyan": "${c.accent}",`,
    `        "terminal.ansi.bright_cyan": "${c.accent}",`,
    `        "terminal.ansi.dim_cyan": "${darken(c.accent, 0.3)}",`,
    `        "terminal.ansi.white": "${e.foreground}",`,
    `        "terminal.ansi.bright_white": "${e.foreground}",`,
    `        "terminal.ansi.dim_white": "${darken(e.foreground, 0.3)}",`,
    `        "scrollbar.show": "auto",`,
    `        "scrollbar_thumb.background": "${darken(e.comment, 0.5)}",`,
    `        "scrollbar.track.background": "transparent",`,
    `        "selection.background": "${e.selection}",`,
    "      },",
    "    },",
    "  ],",
    "}",
  ];

  return lines.join("\n");
}

function generateZedSyntax(palette: HeroPalette): string {
  const e = palette.editor;
  const c = palette.colors;

  const lines: string[] = [
    "{",
    `  "attribute": { "color": "${e.attribute}" },`,
    `  "boolean": { "color": "${e.constant}" },`,
    `  "comment": { "color": "${e.comment}", "font_style": "italic" },`,
    `  "comment.doc": { "color": "${e.comment}", "font_style": "italic" },`,
    `  "constant": { "color": "${e.constant}" },`,
    `  "constructor": { "color": "${e.function}" },`,
    `  "embedded": { "color": "${e.foreground}" },`,
    `  "emphasis": { "font_style": "italic" },`,
    `  "emphasis.strong": { "font_weight": "bold" },`,
    `  "enum": { "color": "${e.enum}" },`,
    `  "function": { "color": "${e.function}" },`,
    `  "hint": { "color": "${e.gutter}" },`,
    `  "keyword": { "color": "${e.keyword}" },`,
    `  "label": { "color": "${e.keyword}" },`,
    `  "link_text": { "color": "${e.function}" },`,
    `  "link_uri": { "color": "${e.string}" },`,
    `  "namespace": { "color": "${e.type}" },`,
    `  "number": { "color": "${e.number}" },`,
    `  "operator": { "color": "${e.operator}" },`,
    `  "predictive": { "color": "${e.foreground}" },`,
    `  "primary": { "color": "${e.foreground}" },`,
    `  "property": { "color": "${e.property}" },`,
    `  "punctuation": { "color": "${e.punctuation}" },`,
    `  "punctuation.bracket": { "color": "${e.punctuation}" },`,
    `  "punctuation.delimiter": { "color": "${e.punctuation}" },`,
    `  "punctuation.list_marker": { "color": "${e.punctuation}" },`,
    `  "punctuation.special": { "color": "${e.punctuation}" },`,
    `  "string": { "color": "${e.string}" },`,
    `  "string.escape": { "color": "${c.accent}" },`,
    `  "string.regex": { "color": "${c.accent}" },`,
    `  "string.special": { "color": "${c.accent}" },`,
    `  "string.special.symbol": { "color": "${c.accent}" },`,
    `  "string.special.url": { "color": "${e.function}" },`,
    `  "tag": { "color": "${e.tag}" },`,
    `  "text.literal": { "color": "${e.string}" },`,
    `  "title": { "color": "${e.foreground}", "font_weight": "bold" },`,
    `  "type": { "color": "${e.type}" },`,
    `  "variable": { "color": "${e.variable}" },`,
    `  "variable.special": { "color": "${e.builtin}" },`,
    "}",
  ];

  return lines.join("\n");
}

export const zedGenerator: PlatformGenerator = {
  name: "zed",
  fileExtension: "json",

  generate(options: GeneratorOptions): GeneratedFile[] {
    const themeContent = generateZedTheme(options.hero);
    const syntaxContent = generateZedSyntax(options.hero);
    const heroSlug = options.hero.hero;
    return [
      { path: `${options.outputDir}/${heroSlug}.json`, content: themeContent },
      { path: `${options.outputDir}/${heroSlug}-syntax.json`, content: syntaxContent },
    ];
  },
};
