import type {
  GeneratedFile,
  GeneratorOptions,
  PlatformGenerator,
} from "@dota-themes/generator-core";
import type { HeroPalette } from "@dota-themes/palettes";

function generateKittyConf(palette: HeroPalette): string {
  const t = palette.terminal;
  const name = palette.metadata.title;

  return `# ${name} theme for Kitty
# Generated by dota-themes
# ${palette.metadata.description}

# Base colors
background ${t.background}
foreground ${t.foreground}
cursor ${t.cursor}
selection_background ${t.selectionBackground}
selection_foreground ${t.foreground}

# Normal colors
color0 ${t.black}
color1 ${t.red}
color2 ${t.green}
color3 ${t.yellow}
color4 ${t.blue}
color5 ${t.magenta}
color6 ${t.cyan}
color7 ${t.white}

# Bright colors
color8 ${t.brightBlack}
color9 ${t.brightRed}
color10 ${t.brightGreen}
color11 ${t.brightYellow}
color12 ${t.brightBlue}
color13 ${t.brightMagenta}
color14 ${t.brightCyan}
color15 ${t.brightWhite}
`;
}

export const kittyGenerator: PlatformGenerator = {
  name: "kitty",
  fileExtension: "conf",

  generate(options: GeneratorOptions): GeneratedFile[] {
    const content = generateKittyConf(options.hero);
    const fileName = `dota-${options.hero.hero}.conf`;
    return [{ path: `${options.outputDir}/${fileName}`, content }];
  },
};
