import type { HeroPalette } from "../schema.js";

export const brewmaster: HeroPalette = {
  hero: "brewmaster",
  metadata: {
    title: "Brewmaster",
    description:
      "The Grandmaster — celestial pandaren warrior who commands the three elemental brews",
    author: "dota-themes",
  },
  colors: {
    background: "#1a1008",
    foreground: "#e0c8a0",
    primary: "#ff8f00",
    secondary: "#ffb74d",
    accent: "#ffd54f",
    error: "#ef5350",
    warning: "#ffab40",
    info: "#4fc3f7",
    success: "#81c784",
  },
  editor: {
    background: "#1a1008",
    foreground: "#e0c8a0",
    gutter: "#201408",
    lineHighlight: "#281a0c",
    selection: "#e65100",
    cursor: "#ffd54f",
    comment: "#8a7a5a",
    keyword: "#ffb74d",
    string: "#ffe0b2",
    number: "#ffd54f",
    function: "#ff8f00",
    variable: "#e0c8a0",
    type: "#ffb74d",
    constant: "#ffd54f",
    operator: "#ffb74d",
    punctuation: "#8a7a5a",
    tag: "#ff8f00",
    attribute: "#ffb74d",
    class: "#ffd54f",
    interface: "#ffb74d",
    enum: "#ffe0b2",
    parameter: "#e0c8a0",
    property: "#ffb74d",
    registry: "#ffd54f",
    builtin: "#ffb74d",
    text: "#e0c8a0",
    whitespace: "#2a2010",
    indentation: "#2a2010",
  },
  terminal: {
    background: "#1a1008",
    foreground: "#e0c8a0",
    cursor: "#ffd54f",
    selectionBackground: "#e65100",
    black: "#1a1008",
    red: "#ef5350",
    green: "#81c784",
    yellow: "#ffab40",
    blue: "#4fc3f7",
    magenta: "#ffb74d",
    cyan: "#ffd54f",
    white: "#e0c8a0",
    brightBlack: "#8a7a5a",
    brightRed: "#ef5350",
    brightGreen: "#81c784",
    brightYellow: "#ffd54f",
    brightBlue: "#4fc3f7",
    brightMagenta: "#ffe0b2",
    brightCyan: "#ffd54f",
    brightWhite: "#fff8e1",
  },
};

export default brewmaster;
