import type { HeroPalette } from "../schema.js";

export const earthSpirit: HeroPalette = {
  hero: "earth-spirit",
  metadata: {
    title: "Earth Spirit",
    description: "The Stonekeeper — ancient guardian who commands the living stone of the earth",
    author: "dota-themes",
  },
  colors: {
    background: "#141210",
    foreground: "#c8bfa8",
    primary: "#8d6e63",
    secondary: "#bcaaa4",
    accent: "#ffab40",
    error: "#ef5350",
    warning: "#ffd54f",
    info: "#80cbc4",
    success: "#81c784",
  },
  editor: {
    background: "#141210",
    foreground: "#c8bfa8",
    gutter: "#1a1816",
    lineHighlight: "#201e1a",
    selection: "#5d4037",
    cursor: "#ffab40",
    comment: "#7a6f62",
    keyword: "#bcaaa4",
    string: "#d7ccc8",
    number: "#ffab40",
    function: "#8d6e63",
    variable: "#c8bfa8",
    type: "#bcaaa4",
    constant: "#ffab40",
    operator: "#bcaaa4",
    punctuation: "#7a6f62",
    tag: "#8d6e63",
    attribute: "#bcaaa4",
    class: "#ffab40",
    interface: "#bcaaa4",
    enum: "#d7ccc8",
    parameter: "#c8bfa8",
    property: "#bcaaa4",
    registry: "#ffab40",
    builtin: "#bcaaa4",
    text: "#c8bfa8",
    whitespace: "#2a2620",
    indentation: "#2a2620",
  },
  terminal: {
    background: "#141210",
    foreground: "#c8bfa8",
    cursor: "#ffab40",
    selectionBackground: "#5d4037",
    black: "#141210",
    red: "#ef5350",
    green: "#81c784",
    yellow: "#ffd54f",
    blue: "#80cbc4",
    magenta: "#bcaaa4",
    cyan: "#ffab40",
    white: "#c8bfa8",
    brightBlack: "#7a6f62",
    brightRed: "#ef5350",
    brightGreen: "#81c784",
    brightYellow: "#ffd54f",
    brightBlue: "#80cbc4",
    brightMagenta: "#d7ccc8",
    brightCyan: "#ffab40",
    brightWhite: "#efebe9",
  },
};

export default earthSpirit;
