import type { HeroPalette } from "../schema.js";

export const invoker: HeroPalette = {
  hero: "invoker",
  metadata: {
    title: "Invoker",
    description: "The Grand Magus — master of the three elements, wielder of arcane brilliance",
    author: "dota-themes",
  },
  colors: {
    background: "#0f0e1a",
    foreground: "#d4ccec",
    primary: "#7c4dff",
    secondary: "#b388ff",
    accent: "#ea80fc",
    error: "#ff5252",
    warning: "#ffd740",
    info: "#40c4ff",
    success: "#69f0ae",
  },
  editor: {
    background: "#0f0e1a",
    foreground: "#d4ccec",
    gutter: "#131225",
    lineHighlight: "#171530",
    selection: "#311b92",
    cursor: "#ea80fc",
    comment: "#6a5fad",
    keyword: "#b388ff",
    string: "#d1c4e9",
    number: "#ea80fc",
    function: "#7c4dff",
    variable: "#d4ccec",
    type: "#b388ff",
    constant: "#ea80fc",
    operator: "#b388ff",
    punctuation: "#6a5fad",
    tag: "#7c4dff",
    attribute: "#b388ff",
    class: "#ea80fc",
    interface: "#b388ff",
    enum: "#d1c4e9",
    parameter: "#d4ccec",
    property: "#b388ff",
    registry: "#ea80fc",
    builtin: "#b388ff",
    text: "#d4ccec",
    whitespace: "#1e1a3a",
    indentation: "#1e1a3a",
  },
  terminal: {
    background: "#0f0e1a",
    foreground: "#d4ccec",
    cursor: "#ea80fc",
    selectionBackground: "#311b92",
    black: "#0f0e1a",
    red: "#ff5252",
    green: "#69f0ae",
    yellow: "#ffd740",
    blue: "#40c4ff",
    magenta: "#b388ff",
    cyan: "#ea80fc",
    white: "#d4ccec",
    brightBlack: "#6a5fad",
    brightRed: "#ff5252",
    brightGreen: "#69f0ae",
    brightYellow: "#ffd740",
    brightBlue: "#40c4ff",
    brightMagenta: "#d1c4e9",
    brightCyan: "#ea80fc",
    brightWhite: "#ede7f6",
  },
};

export default invoker;
