-- Brewmaster theme for Neovim
-- Generated by dota-themes
-- The Grandmaster — celestial pandaren warrior who commands the three elemental brews

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-brewmaster"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#e0c8a0", bg = "#1a1008" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#e0c8a0", bg = "#1a1008" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#e0c8a0", bg = "#1a1008" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#1a1008", bg = "#ffd54f" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#281a0c" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#281a0c" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#e65100" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#e65100" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#201408" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#ffd54f" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#1a1008" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#1a1008" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#281a0c" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#8a7a5a", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Label", { fg = "#ffb74d" })

vim.api.nvim_set_hl(0, "String", { fg = "#ffe0b2" })
vim.api.nvim_set_hl(0, "Character", { fg = "#ffe0b2" })

vim.api.nvim_set_hl(0, "Number", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "Float", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#ffd54f" })

vim.api.nvim_set_hl(0, "Function", { fg = "#ff8f00" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#e0c8a0" })

vim.api.nvim_set_hl(0, "Type", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#ffb74d" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "Define", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Include", { fg = "#ffb74d" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#8a7a5a" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#ff8f00" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#ffb74d" })

vim.api.nvim_set_hl(0, "Class", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#ffe0b2" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#ffe0b2" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#e0c8a0" })
vim.api.nvim_set_hl(0, "Property", { fg = "#ffb74d" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#ffb74d" })

vim.api.nvim_set_hl(0, "Special", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#201408" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#4fc3f7" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#81c784" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#ffd54f", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#1a1008", bg = "#ffd54f" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#1a1008", bg = "#ffd54f" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#e0c8a0", bg = "#190f08" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#e0c8a0", bg = "#e65100" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#180f07" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#8a7a5a" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#e0c8a0", bg = "#180f07" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#8a7a5a", bg = "#180f07" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#1c1109" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#190f08" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#190f08" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#e0c8a0", bg = "#1a1008" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#ff8f00", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#ff8f00" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#81c784" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#4fc3f7" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#81c784" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#ffab40", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#4fc3f7", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#81c784", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#5a8b5c" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#a73a38" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#3789ad" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#3f9cc6" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#81c784" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#4fc3f7" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#ef5350" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#8a7a5a" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#e0c8a0", bg = "#e65100" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#2a2010" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#e0c8a0", bg = "#1a1008" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#281a0c" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#ff8f00" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#e0c8a0" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#190f08" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#e65100" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#8a7a5a" })