-- Lich theme for Neovim
-- Generated by dota-themes
-- The Frost Mage — Frost Blast explodes with ice, Frost Shield protects with frozen barriers, Sinister Gaze drains souls with dark magic, Sacrifice harvests mana from the living, Chain Frost bounces death between enemies

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-lich"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#a8c4d8", bg = "#060d14" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#a8c4d8", bg = "#060d14" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#a8c4d8", bg = "#060d14" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#060d14", bg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#0c1722" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#0c1722" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#162a40" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#162a40" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#0a131c" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#5ec4e8" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#060d14" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#060d14" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#0c1722" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#3e5868", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Label", { fg = "#6e5ec4" })

vim.api.nvim_set_hl(0, "String", { fg = "#7ad4f0" })
vim.api.nvim_set_hl(0, "Character", { fg = "#7ad4f0" })

vim.api.nvim_set_hl(0, "Number", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "Float", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#4a8ab4" })

vim.api.nvim_set_hl(0, "Function", { fg = "#8ab4d8" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#a8c4d8" })

vim.api.nvim_set_hl(0, "Type", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#6e5ec4" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#4a8ab4" })
vim.api.nvim_set_hl(0, "Define", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Include", { fg = "#6e5ec4" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#3e5868" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#3e5868" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#6e5ec4" })

vim.api.nvim_set_hl(0, "Class", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#4a8ab4" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#4a8ab4" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#88b4cc" })
vim.api.nvim_set_hl(0, "Property", { fg = "#6aa0c0" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#7ad4f0" })

vim.api.nvim_set_hl(0, "Special", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#0a131c" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#d44e5a" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#5ec4e8" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#6e5ec4", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#060d14", bg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#060d14", bg = "#5ec4e8" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#a8c4d8", bg = "#060c13" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#a8c4d8", bg = "#162a40" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#060c12" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#3e5868" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#a8c4d8", bg = "#060c12" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#3e5868", bg = "#060c12" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#060e16" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#060c13" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#060c13" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#a8c4d8", bg = "#060d14" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#5ec4e8", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#5ec4e8" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#d44e5a" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#5ec4e8" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#d44e5a" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#5ec4e8" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#d44e5a", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#6e5ec4", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#5ec4e8", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#5ec4e8", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#4289a2" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#94373f" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#4289a2" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#4b9dba" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#d44e5a" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#3e5868" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#a8c4d8", bg = "#162a40" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#162a40" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#a8c4d8", bg = "#060d14" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#0c1722" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#6e5ec4" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#5ec4e8" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#a8c4d8" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#060c13" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#162a40" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#3e5868" })