-- Necrophos theme for Neovim
-- Generated by dota-themes
-- The Radiant Reaper — Death Pulse heals allies and damages enemies, Ghost Shroud cloaks in ethereal mist, Heartstopper Aura drains life, Reaper's Scythe harvests souls

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-necrophos"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#c8d8d0", bg = "#0b1215" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#c8d8d0", bg = "#0b1215" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#c8d8d0", bg = "#0b1215" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#0b1215", bg = "#5ccf8e" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#101a1f" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#101a1f" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#1a3a30" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#1a3a30" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#0e161a" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#5ccf8e" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0b1215" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#0b1215" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#101a1f" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#5a6b63", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "Label", { fg = "#9272c4" })

vim.api.nvim_set_hl(0, "String", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "Character", { fg = "#c9a94e" })

vim.api.nvim_set_hl(0, "Number", { fg = "#b8944a" })
vim.api.nvim_set_hl(0, "Float", { fg = "#b8944a" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#b8944a" })

vim.api.nvim_set_hl(0, "Function", { fg = "#4a9e5e" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#c8d8d0" })

vim.api.nvim_set_hl(0, "Type", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#6aadaf" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#b8944a" })
vim.api.nvim_set_hl(0, "Define", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#9272c4" })
vim.api.nvim_set_hl(0, "Include", { fg = "#9272c4" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#5a6b63" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#5a6b63" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#5ccf8e" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#6aadaf" })

vim.api.nvim_set_hl(0, "Class", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#b8944a" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#b8944a" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#8bbaa0" })
vim.api.nvim_set_hl(0, "Property", { fg = "#7ab89a" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#5ccf8e" })

vim.api.nvim_set_hl(0, "Special", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#0e161a" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#bf4e4e" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#5ccf8e" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#c9a94e", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#0b1215", bg = "#c9a94e" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0b1215", bg = "#5ccf8e" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#c8d8d0", bg = "#0a1114" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#c8d8d0", bg = "#1a3a30" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#0a1113" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#5a6b63" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#c8d8d0", bg = "#0a1113" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#5a6b63", bg = "#0a1113" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#0c1317" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#0a1114" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0a1114" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#c8d8d0", bg = "#0b1215" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#5ccf8e", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#5ccf8e" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#bf4e4e" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#5ccf8e" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#bf4e4e" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#5ccf8e" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#bf4e4e", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#c9a94e", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#6aadaf", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#5ccf8e", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#409163" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#863737" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#4a797a" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#558a8c" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#5ccf8e" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#6aadaf" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#bf4e4e" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#5a6b63" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#c8d8d0", bg = "#1a3a30" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#1a3a30" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#c8d8d0", bg = "#0b1215" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#101a1f" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#c9a94e" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#5ccf8e" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#c8d8d0" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#0a1114" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#1a3a30" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#5a6b63" })