-- Necrophos theme for Neovim
-- Generated by dota-themes
-- The Radiant Reaper — a sickly green death priest who drains life from the living

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-necrophos"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#D7E5DD", bg = "#0f191f" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#D7E5DD", bg = "#0f191f" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#D7E5DD", bg = "#0f191f" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#0f191f", bg = "#6EE7A8" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#142630" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#142630" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#1d534d" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#1d534d" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#142630" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#6EE7A8" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0f191f" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#0f191f" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#142630" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#66736D", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "Label", { fg = "#8c7ac2" })

vim.api.nvim_set_hl(0, "String", { fg = "#C9A45A" })
vim.api.nvim_set_hl(0, "Character", { fg = "#C9A45A" })

vim.api.nvim_set_hl(0, "Number", { fg = "#AF8B43" })
vim.api.nvim_set_hl(0, "Float", { fg = "#AF8B43" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#AF8B43" })

vim.api.nvim_set_hl(0, "Function", { fg = "#6E9440" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#D7E5DD" })

vim.api.nvim_set_hl(0, "Type", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#69C7B5" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#AF8B43" })
vim.api.nvim_set_hl(0, "Define", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#8c7ac2" })
vim.api.nvim_set_hl(0, "Include", { fg = "#8c7ac2" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#66736D" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#66736D" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#6EE7A8" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#69C7B5" })

vim.api.nvim_set_hl(0, "Class", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#AF8B43" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#AF8B43" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#B6D2C8" })
vim.api.nvim_set_hl(0, "Property", { fg = "#A4E2D0" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#6EE7A8" })

vim.api.nvim_set_hl(0, "Special", { fg = "#78D6AE" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#78D6AE" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#142630" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#c25c5c" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#C9A45A" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#6EE7A8" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#78D6AE", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#0f191f", bg = "#78D6AE" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0f191f", bg = "#6EE7A8" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#D7E5DD", bg = "#0e181d" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#D7E5DD", bg = "#1d534d" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#0e171d" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#66736D" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#D7E5DD", bg = "#0e171d" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#66736D", bg = "#0e171d" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#101b21" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#0e181d" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0e181d" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#D7E5DD", bg = "#0f191f" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#54C892", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#54C892" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#c25c5c" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#C9A45A" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#6EE7A8" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#c25c5c" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#C9A45A" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#6EE7A8" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#c25c5c", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#C9A45A", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#69C7B5", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#6EE7A8", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#4da276" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#884040" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#4a8b7f" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#549f91" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#6EE7A8" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#69C7B5" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#c25c5c" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#66736D" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#78D6AE" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#D7E5DD", bg = "#1d534d" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#1f4d4d" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#D7E5DD", bg = "#0f191f" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#142630" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#78D6AE" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#54C892" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#D7E5DD" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#0e181d" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#1d534d" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#66736D" })