-- Lich theme for Neovim
-- Generated by dota-themes
-- The Frost Mage — ancient frost sorcerer, lord of the frozen wastes

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-lich"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#b8d4e3", bg = "#0a1218" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#b8d4e3", bg = "#0a1218" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#b8d4e3", bg = "#0a1218" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#0a1218", bg = "#29b6f6" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#101e28" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#101e28" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#0d47a1" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#0d47a1" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#0d1820" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#29b6f6" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0a1218" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#0a1218" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#101e28" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#4a6a7a", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Label", { fg = "#81d4fa" })

vim.api.nvim_set_hl(0, "String", { fg = "#b3e5fc" })
vim.api.nvim_set_hl(0, "Character", { fg = "#b3e5fc" })

vim.api.nvim_set_hl(0, "Number", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Float", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#29b6f6" })

vim.api.nvim_set_hl(0, "Function", { fg = "#4fc3f7" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#b8d4e3" })

vim.api.nvim_set_hl(0, "Type", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#81d4fa" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Define", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Include", { fg = "#81d4fa" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#4a6a7a" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#4fc3f7" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#81d4fa" })

vim.api.nvim_set_hl(0, "Class", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#81d4fa" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#b3e5fc" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#b3e5fc" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#b8d4e3" })
vim.api.nvim_set_hl(0, "Property", { fg = "#81d4fa" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#81d4fa" })

vim.api.nvim_set_hl(0, "Special", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#0d1820" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#4dd0e1" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#81c784" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#29b6f6", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#0a1218", bg = "#29b6f6" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0a1218", bg = "#29b6f6" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#b8d4e3", bg = "#0a1117" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#b8d4e3", bg = "#0d47a1" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#091116" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#4a6a7a" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#b8d4e3", bg = "#091116" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#4a6a7a", bg = "#091116" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#0b131a" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#0a1117" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0a1117" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#b8d4e3", bg = "#0a1218" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#4fc3f7", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#4fc3f7" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#81c784" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ffb74d" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#4dd0e1" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#81c784" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#ffb74d", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#4dd0e1", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#81c784", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#5a8b5c" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#a73a38" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#36929e" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#3ea6b4" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#81c784" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#4dd0e1" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#ef5350" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#4a6a7a" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#b8d4e3", bg = "#0d47a1" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#1a2a35" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#b8d4e3", bg = "#0a1218" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#101e28" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#4fc3f7" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#b8d4e3" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#0a1117" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#0d47a1" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#4a6a7a" })