-- Brewmaster theme for Neovim
-- Generated by dota-themes
-- The Grandmaster — Thunder Clap shakes the earth, Cinder Brew ignites foes, Drunken Brawler sways like wind, Primal Split summons Earth, Storm, and Fire

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-brewmaster"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#d4bfa0", bg = "#15100c" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#d4bfa0", bg = "#15100c" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#d4bfa0", bg = "#15100c" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#15100c", bg = "#e6b84a" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1e1812" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#1e1812" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#3a2818" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#3a2818" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#1a140e" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#e6b84a" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#15100c" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#15100c" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#1e1812" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#7a6e58", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Label", { fg = "#c45c3a" })

vim.api.nvim_set_hl(0, "String", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "Character", { fg = "#e6b84a" })

vim.api.nvim_set_hl(0, "Number", { fg = "#d4782a" })
vim.api.nvim_set_hl(0, "Float", { fg = "#d4782a" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#8a6e4a" })

vim.api.nvim_set_hl(0, "Function", { fg = "#d4782a" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#d4bfa0" })

vim.api.nvim_set_hl(0, "Type", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#5a9ec4" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#8a6e4a" })
vim.api.nvim_set_hl(0, "Define", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Include", { fg = "#c45c3a" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#7a6e58" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#7a6e58" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#5a9ec4" })

vim.api.nvim_set_hl(0, "Class", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#8a6e4a" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#8a6e4a" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#b8a888" })
vim.api.nvim_set_hl(0, "Property", { fg = "#9a8a6a" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#e6b84a" })

vim.api.nvim_set_hl(0, "Special", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#1a140e" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#7a9e5a" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#e6b84a", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#15100c", bg = "#e6b84a" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#15100c", bg = "#e6b84a" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#d4bfa0", bg = "#140f0b" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#d4bfa0", bg = "#3a2818" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#130f0b" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#7a6e58" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#d4bfa0", bg = "#130f0b" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#7a6e58", bg = "#130f0b" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#17110d" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#140f0b" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#140f0b" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#d4bfa0", bg = "#15100c" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#d4782a", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#d4782a" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#7a9e5a" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#c45c3a" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#7a9e5a" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#c45c3a", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#e6b84a", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#5a9ec4", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#7a9e5a", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#556f3f" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#894029" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#3f6f89" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#487e9d" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#7a9e5a" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#5a9ec4" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#c45c3a" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#7a6e58" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#d4bfa0", bg = "#3a2818" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#3a2818" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#d4bfa0", bg = "#15100c" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#1e1812" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#e6b84a" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#d4782a" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#d4bfa0" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#140f0b" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#3a2818" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#7a6e58" })