-- Earth Spirit theme for Neovim
-- Generated by dota-themes
-- The Stonekeeper — ancient guardian who commands the living stone of the earth

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-earth-spirit"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#c8bfa8", bg = "#141210" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#c8bfa8", bg = "#141210" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#c8bfa8", bg = "#141210" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#141210", bg = "#ffab40" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#201e1a" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#201e1a" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#5d4037" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#5d4037" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#1a1816" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#ffab40" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#141210" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#141210" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#201e1a" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#7a6f62", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Label", { fg = "#bcaaa4" })

vim.api.nvim_set_hl(0, "String", { fg = "#d7ccc8" })
vim.api.nvim_set_hl(0, "Character", { fg = "#d7ccc8" })

vim.api.nvim_set_hl(0, "Number", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "Float", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#ffab40" })

vim.api.nvim_set_hl(0, "Function", { fg = "#8d6e63" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#c8bfa8" })

vim.api.nvim_set_hl(0, "Type", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#bcaaa4" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "Define", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Include", { fg = "#bcaaa4" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#7a6f62" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#8d6e63" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#bcaaa4" })

vim.api.nvim_set_hl(0, "Class", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#bcaaa4" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#d7ccc8" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#d7ccc8" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#c8bfa8" })
vim.api.nvim_set_hl(0, "Property", { fg = "#bcaaa4" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#bcaaa4" })

vim.api.nvim_set_hl(0, "Special", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#1a1816" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#80cbc4" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#81c784" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#ffab40", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#141210", bg = "#ffab40" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#141210", bg = "#ffab40" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#c8bfa8", bg = "#13110f" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#c8bfa8", bg = "#5d4037" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#12110f" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#7a6f62" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#c8bfa8", bg = "#12110f" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#7a6f62", bg = "#12110f" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#161311" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#13110f" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#13110f" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#c8bfa8", bg = "#141210" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#8d6e63", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#8d6e63" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#81c784" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ffd54f" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#80cbc4" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#81c784" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#ffd54f", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#80cbc4", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#81c784", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#5a8b5c" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#a73a38" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#5a8e89" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#66a29d" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#81c784" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#80cbc4" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#ef5350" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#7a6f62" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#c8bfa8", bg = "#5d4037" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#2a2620" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#c8bfa8", bg = "#141210" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#201e1a" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#ffab40" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#8d6e63" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#c8bfa8" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#13110f" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#5d4037" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#7a6f62" })