-- Invoker theme for Neovim
-- Generated by dota-themes
-- The Grand Magus — master of the three elements, wielder of arcane brilliance

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-invoker"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#d4ccec", bg = "#0f0e1a" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#d4ccec", bg = "#0f0e1a" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#d4ccec", bg = "#0f0e1a" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#0f0e1a", bg = "#ea80fc" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#171530" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#171530" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#311b92" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#311b92" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#131225" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#ea80fc" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0f0e1a" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#0f0e1a" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#171530" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#6a5fad", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Label", { fg = "#b388ff" })

vim.api.nvim_set_hl(0, "String", { fg = "#d1c4e9" })
vim.api.nvim_set_hl(0, "Character", { fg = "#d1c4e9" })

vim.api.nvim_set_hl(0, "Number", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "Float", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#ea80fc" })

vim.api.nvim_set_hl(0, "Function", { fg = "#7c4dff" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#d4ccec" })

vim.api.nvim_set_hl(0, "Type", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#b388ff" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "Define", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Include", { fg = "#b388ff" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#6a5fad" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#7c4dff" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#b388ff" })

vim.api.nvim_set_hl(0, "Class", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#b388ff" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#d1c4e9" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#d1c4e9" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#d4ccec" })
vim.api.nvim_set_hl(0, "Property", { fg = "#b388ff" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#b388ff" })

vim.api.nvim_set_hl(0, "Special", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#131225" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#ff5252" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#ffd740" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#40c4ff" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#69f0ae" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#ea80fc", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#0f0e1a", bg = "#ea80fc" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0f0e1a", bg = "#ea80fc" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#d4ccec", bg = "#0e0d19" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#d4ccec", bg = "#311b92" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#0e0d18" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#6a5fad" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#d4ccec", bg = "#0e0d18" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#6a5fad", bg = "#0e0d18" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#100f1c" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#0e0d19" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0e0d19" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#d4ccec", bg = "#0f0e1a" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#7c4dff", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#7c4dff" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#ff5252" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#ffd740" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#69f0ae" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ff5252" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ffd740" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#40c4ff" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#69f0ae" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#ff5252", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#ffd740", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#40c4ff", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#69f0ae", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#4aa87a" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#b33939" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#2d89b3" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#339dcc" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#69f0ae" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#40c4ff" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#ff5252" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#6a5fad" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#d4ccec", bg = "#311b92" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#1e1a3a" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#d4ccec", bg = "#0f0e1a" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#171530" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#ea80fc" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#7c4dff" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#d4ccec" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#0e0d19" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#311b92" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#6a5fad" })