-- Kunkka theme for Neovim
-- Generated by dota-themes
-- The Admiral — master of the tides, commander of the ghostly armada

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-kunkka"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#b0c4de", bg = "#0a1520" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#b0c4de", bg = "#0a1520" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#b0c4de", bg = "#0a1520" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#0a1520", bg = "#29b6f6" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#102030" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#102030" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#1565c0" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#1565c0" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#0d1b2a" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#29b6f6" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0a1520" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#0a1520" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#102030" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#546e7a", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Label", { fg = "#90caf9" })

vim.api.nvim_set_hl(0, "String", { fg = "#b3e5fc" })
vim.api.nvim_set_hl(0, "Character", { fg = "#b3e5fc" })

vim.api.nvim_set_hl(0, "Number", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Float", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#29b6f6" })

vim.api.nvim_set_hl(0, "Function", { fg = "#42a5f5" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#b0c4de" })

vim.api.nvim_set_hl(0, "Type", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#90caf9" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Define", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Include", { fg = "#90caf9" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#546e7a" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#42a5f5" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#90caf9" })

vim.api.nvim_set_hl(0, "Class", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#90caf9" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#b3e5fc" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#b3e5fc" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#b0c4de" })
vim.api.nvim_set_hl(0, "Property", { fg = "#90caf9" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#90caf9" })

vim.api.nvim_set_hl(0, "Special", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#0d1b2a" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#ffa726" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#26c6da" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#66bb6a" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#29b6f6", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#0a1520", bg = "#29b6f6" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0a1520", bg = "#29b6f6" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#b0c4de", bg = "#0a141e" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#b0c4de", bg = "#1565c0" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#09131d" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#546e7a" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#b0c4de", bg = "#09131d" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#546e7a", bg = "#09131d" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#0b1723" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#0a141e" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0a141e" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#b0c4de", bg = "#0a1520" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#42a5f5", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#42a5f5" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#ffa726" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#66bb6a" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ffa726" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#26c6da" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#66bb6a" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#ffa726", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#26c6da", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#66bb6a", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#47834a" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#a73a38" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#1b8b99" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#1e9eae" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#66bb6a" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#26c6da" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#ef5350" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#546e7a" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#b0c4de", bg = "#1565c0" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#1a3040" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#b0c4de", bg = "#0a1520" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#102030" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#29b6f6" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#42a5f5" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#b0c4de" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#0a141e" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#1565c0" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#546e7a" })