-- Arc Warden theme for Neovim
-- Generated by dota-themes
-- The Primordial — Flux unleashes unstable electric energy, Magnetic Field conjures a cyan barrier, Spark Wraith summons spectral spirits, Tempest Double duplicates cosmic power

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-arc-warden"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#b8cce0", bg = "#080c16" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#b8cce0", bg = "#080c16" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#b8cce0", bg = "#080c16" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#080c16", bg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#0e1424" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#0e1424" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#1a2a48" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#1a2a48" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#0c1120" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#3cc8e8" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#080c16" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#080c16" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#0e1424" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#4a5a72", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "Label", { fg = "#9872d0" })

vim.api.nvim_set_hl(0, "String", { fg = "#38b2a8" })
vim.api.nvim_set_hl(0, "Character", { fg = "#38b2a8" })

vim.api.nvim_set_hl(0, "Number", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "Float", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#c890e0" })

vim.api.nvim_set_hl(0, "Function", { fg = "#5ad4e8" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#b8cce0" })

vim.api.nvim_set_hl(0, "Type", { fg = "#7888d4" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#7888d4" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#7888d4" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#c890e0" })
vim.api.nvim_set_hl(0, "Define", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "Include", { fg = "#9872d0" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#4a5a72" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#4a5a72" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#38b2a8" })

vim.api.nvim_set_hl(0, "Class", { fg = "#7888d4" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#7888d4" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#c890e0" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#c890e0" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#88b8d0" })
vim.api.nvim_set_hl(0, "Property", { fg = "#60a8c0" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#38b2a8" })

vim.api.nvim_set_hl(0, "Special", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#0c1120" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#d05868" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#d8a848" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#38b2a8" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#9872d0", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#080c16", bg = "#9872d0" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#080c16", bg = "#3cc8e8" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#b8cce0", bg = "#080b15" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#b8cce0", bg = "#1a2a48" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#070b14" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#4a5a72" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#b8cce0", bg = "#070b14" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#4a5a72", bg = "#070b14" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#090d18" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#080b15" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#080b15" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#b8cce0", bg = "#080c16" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#3cc8e8", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#3cc8e8" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#d05868" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#d8a848" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#38b2a8" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#d05868" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#d8a848" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#38b2a8" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#d05868", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#d8a848", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#3cc8e8", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#38b2a8", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#277d76" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#923e49" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#2a8ca2" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#30a0ba" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#38b2a8" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#d05868" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#4a5a72" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#b8cce0", bg = "#1a2a48" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#1a2a48" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#b8cce0", bg = "#080c16" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#0e1424" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#9872d0" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#3cc8e8" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#b8cce0" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#080b15" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#1a2a48" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#4a5a72" })