-- Invoker theme for Neovim
-- Generated by dota-themes
-- The Grand Magus — master of the three elements, wielder of arcane brilliance

local theme_name = "dota-invoker"

local theme = {
  colors = {
    base = "#0f0e1a",
    mantle = "#0e0d19",
    surface0 = "#0f0e1b",
    surface1 = "#100f1c",
    surface2 = "#100f1c",
    overlay0 = "#6a5fad",
    overlay1 = "#131225",
    overlay2 = "#1e1a3a",
    text = "#d4ccec",
    subtext0 = "#b4adc9",
    subtext1 = "#c3bcd9",
    primary = "#7c4dff",
    secondary = "#b388ff",
    accent = "#ea80fc",
    error = "#ff5252",
    warning = "#ffd740",
    info = "#40c4ff",
    success = "#69f0ae",
    cursor = "#ea80fc",
    selection = "#311b92",
    lineHighlight = "#171530",
    gutter = "#131225",
  },
  highlights = {
    Normal = { fg = "#d4ccec", bg = "#0f0e1a" },
    NormalFloat = { fg = "#d4ccec", bg = "#0f0e1a" },
    NormalNC = { fg = "#d4ccec", bg = "#0f0e1a" },

    Cursor = { fg = "#0f0e1a", bg = "#ea80fc" },
    CursorLine = { bg = "#171530" },
    CursorColumn = { bg = "#171530" },

    Visual = { bg = "#311b92" },
    VisualNOS = { bg = "#311b92" },

    LineNr = { fg = "#131225" },
    CursorLineNr = { fg = "#ea80fc" },

    SignColumn = { bg = "#0f0e1a" },
    FoldColumn = { bg = "#0f0e1a" },
    Folded = { bg = "#171530" },

    Comment = { fg = "#6a5fad", italic = true },
    Keyword = { fg = "#b388ff" },
    Statement = { fg = "#b388ff" },
    Conditional = { fg = "#b388ff" },
    Repeat = { fg = "#b388ff" },
    Label = { fg = "#b388ff" },

    String = { fg = "#d1c4e9" },
    Character = { fg = "#d1c4e9" },

    Number = { fg = "#ea80fc" },
    Float = { fg = "#ea80fc" },
    Boolean = { fg = "#ea80fc" },

    Function = { fg = "#7c4dff" },

    Identifier = { fg = "#d4ccec" },

    Type = { fg = "#b388ff" },
    Structure = { fg = "#b388ff" },
    Typedef = { fg = "#b388ff" },

    Constant = { fg = "#ea80fc" },
    Define = { fg = "#b388ff" },
    Macro = { fg = "#b388ff" },
    PreCondit = { fg = "#b388ff" },
    PreProc = { fg = "#b388ff" },
    Include = { fg = "#b388ff" },

    Operator = { fg = "#b388ff" },
    Delimiter = { fg = "#6a5fad" },

    Tag = { fg = "#7c4dff" },
    Attribute = { fg = "#b388ff" },

    Class = { fg = "#ea80fc" },
    Interface = { fg = "#b388ff" },
    Enum = { fg = "#d1c4e9" },
    EnumMember = { fg = "#d1c4e9" },

    Parameter = { fg = "#d4ccec" },
    Property = { fg = "#b388ff" },

    Builtin = { fg = "#b388ff" },

    Special = { fg = "#ea80fc" },
    SpecialChar = { fg = "#ea80fc" },
    SpecialKey = { fg = "#131225" },

    Error = { fg = "#ff5252" },
    WarningMsg = { fg = "#ffd740" },
    InfoMsg = { fg = "#40c4ff" },
    MoreMsg = { fg = "#69f0ae" },

    Todo = { fg = "#ea80fc", bold = true },
    Search = { fg = "#0f0e1a", bg = "#ea80fc" },
    IncSearch = { fg = "#0f0e1a", bg = "#ea80fc" },

    Pmenu = { fg = "#d4ccec", bg = "#0e0d19" },
    PmenuSel = { fg = "#d4ccec", bg = "#311b92" },
    PmenuSbar = { bg = "#0e0d18" },
    PmenuThumb = { bg = "#6a5fad" },

    StatusLine = { fg = "#d4ccec", bg = "#0e0d18" },
    StatusLineNC = { fg = "#6a5fad", bg = "#0e0d18" },
    WinSeparator = { fg = "#100f1c" },

    TabLine = { bg = "#0e0d19" },
    TabLineFill = { bg = "#0e0d19" },
    TabLineSel = { fg = "#d4ccec", bg = "#0f0e1a" },

    Title = { fg = "#7c4dff", bold = true },
    Directory = { fg = "#7c4dff" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#ff5252" },
    HealthWarning = { fg = "#ffd740" },
    HealthSuccess = { fg = "#69f0ae" },

    DiagnosticError = { fg = "#ff5252" },
    DiagnosticWarn = { fg = "#ffd740" },
    DiagnosticInfo = { fg = "#40c4ff" },
    DiagnosticHint = { fg = "#69f0ae" },

    DiffAdd = { bg = "#4aa87a" },
    DiffDelete = { bg = "#b33939" },
    DiffChange = { bg = "#2d89b3" },
    DiffText = { bg = "#339dcc" },

    GitSignsAdd = { fg = "#69f0ae" },
    GitSignsChange = { fg = "#40c4ff" },
    GitSignsDelete = { fg = "#ff5252" },
  },
}

return theme