-- Earth Spirit theme for Neovim
-- Generated by dota-themes
-- The Stonekeeper — ancient guardian who commands the living stone of the earth

local theme_name = "dota-earth-spirit"

local theme = {
  colors = {
    base = "#141210",
    mantle = "#13110f",
    surface0 = "#151310",
    surface1 = "#151311",
    surface2 = "#161411",
    overlay0 = "#7a6f62",
    overlay1 = "#1a1816",
    overlay2 = "#2a2620",
    text = "#c8bfa8",
    subtext0 = "#aaa28f",
    subtext1 = "#b8b09b",
    primary = "#8d6e63",
    secondary = "#bcaaa4",
    accent = "#ffab40",
    error = "#ef5350",
    warning = "#ffd54f",
    info = "#80cbc4",
    success = "#81c784",
    cursor = "#ffab40",
    selection = "#5d4037",
    lineHighlight = "#201e1a",
    gutter = "#1a1816",
  },
  highlights = {
    Normal = { fg = "#c8bfa8", bg = "#141210" },
    NormalFloat = { fg = "#c8bfa8", bg = "#141210" },
    NormalNC = { fg = "#c8bfa8", bg = "#141210" },

    Cursor = { fg = "#141210", bg = "#ffab40" },
    CursorLine = { bg = "#201e1a" },
    CursorColumn = { bg = "#201e1a" },

    Visual = { bg = "#5d4037" },
    VisualNOS = { bg = "#5d4037" },

    LineNr = { fg = "#1a1816" },
    CursorLineNr = { fg = "#ffab40" },

    SignColumn = { bg = "#141210" },
    FoldColumn = { bg = "#141210" },
    Folded = { bg = "#201e1a" },

    Comment = { fg = "#7a6f62", italic = true },
    Keyword = { fg = "#bcaaa4" },
    Statement = { fg = "#bcaaa4" },
    Conditional = { fg = "#bcaaa4" },
    Repeat = { fg = "#bcaaa4" },
    Label = { fg = "#bcaaa4" },

    String = { fg = "#d7ccc8" },
    Character = { fg = "#d7ccc8" },

    Number = { fg = "#ffab40" },
    Float = { fg = "#ffab40" },
    Boolean = { fg = "#ffab40" },

    Function = { fg = "#8d6e63" },

    Identifier = { fg = "#c8bfa8" },

    Type = { fg = "#bcaaa4" },
    Structure = { fg = "#bcaaa4" },
    Typedef = { fg = "#bcaaa4" },

    Constant = { fg = "#ffab40" },
    Define = { fg = "#bcaaa4" },
    Macro = { fg = "#bcaaa4" },
    PreCondit = { fg = "#bcaaa4" },
    PreProc = { fg = "#bcaaa4" },
    Include = { fg = "#bcaaa4" },

    Operator = { fg = "#bcaaa4" },
    Delimiter = { fg = "#7a6f62" },

    Tag = { fg = "#8d6e63" },
    Attribute = { fg = "#bcaaa4" },

    Class = { fg = "#ffab40" },
    Interface = { fg = "#bcaaa4" },
    Enum = { fg = "#d7ccc8" },
    EnumMember = { fg = "#d7ccc8" },

    Parameter = { fg = "#c8bfa8" },
    Property = { fg = "#bcaaa4" },

    Builtin = { fg = "#bcaaa4" },

    Special = { fg = "#ffab40" },
    SpecialChar = { fg = "#ffab40" },
    SpecialKey = { fg = "#1a1816" },

    Error = { fg = "#ef5350" },
    WarningMsg = { fg = "#ffd54f" },
    InfoMsg = { fg = "#80cbc4" },
    MoreMsg = { fg = "#81c784" },

    Todo = { fg = "#ffab40", bold = true },
    Search = { fg = "#141210", bg = "#ffab40" },
    IncSearch = { fg = "#141210", bg = "#ffab40" },

    Pmenu = { fg = "#c8bfa8", bg = "#13110f" },
    PmenuSel = { fg = "#c8bfa8", bg = "#5d4037" },
    PmenuSbar = { bg = "#12110f" },
    PmenuThumb = { bg = "#7a6f62" },

    StatusLine = { fg = "#c8bfa8", bg = "#12110f" },
    StatusLineNC = { fg = "#7a6f62", bg = "#12110f" },
    WinSeparator = { fg = "#161311" },

    TabLine = { bg = "#13110f" },
    TabLineFill = { bg = "#13110f" },
    TabLineSel = { fg = "#c8bfa8", bg = "#141210" },

    Title = { fg = "#8d6e63", bold = true },
    Directory = { fg = "#8d6e63" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#ef5350" },
    HealthWarning = { fg = "#ffd54f" },
    HealthSuccess = { fg = "#81c784" },

    DiagnosticError = { fg = "#ef5350" },
    DiagnosticWarn = { fg = "#ffd54f" },
    DiagnosticInfo = { fg = "#80cbc4" },
    DiagnosticHint = { fg = "#81c784" },

    DiffAdd = { bg = "#5a8b5c" },
    DiffDelete = { bg = "#a73a38" },
    DiffChange = { bg = "#5a8e89" },
    DiffText = { bg = "#66a29d" },

    GitSignsAdd = { fg = "#81c784" },
    GitSignsChange = { fg = "#80cbc4" },
    GitSignsDelete = { fg = "#ef5350" },
  },
}

return theme