-- Kunkka theme for Neovim
-- Generated by dota-themes
-- The Admiral — master of the tides, commander of the ghostly armada

local theme_name = "dota-kunkka"

local theme = {
  colors = {
    base = "#0a1520",
    mantle = "#0a141e",
    surface0 = "#0a1621",
    surface1 = "#0b1622",
    surface2 = "#0b1723",
    overlay0 = "#546e7a",
    overlay1 = "#0d1b2a",
    overlay2 = "#1a3040",
    text = "#b0c4de",
    subtext0 = "#96a7bd",
    subtext1 = "#a2b4cc",
    primary = "#42a5f5",
    secondary = "#90caf9",
    accent = "#29b6f6",
    error = "#ef5350",
    warning = "#ffa726",
    info = "#26c6da",
    success = "#66bb6a",
    cursor = "#29b6f6",
    selection = "#1565c0",
    lineHighlight = "#102030",
    gutter = "#0d1b2a",
  },
  highlights = {
    Normal = { fg = "#b0c4de", bg = "#0a1520" },
    NormalFloat = { fg = "#b0c4de", bg = "#0a1520" },
    NormalNC = { fg = "#b0c4de", bg = "#0a1520" },

    Cursor = { fg = "#0a1520", bg = "#29b6f6" },
    CursorLine = { bg = "#102030" },
    CursorColumn = { bg = "#102030" },

    Visual = { bg = "#1565c0" },
    VisualNOS = { bg = "#1565c0" },

    LineNr = { fg = "#0d1b2a" },
    CursorLineNr = { fg = "#29b6f6" },

    SignColumn = { bg = "#0a1520" },
    FoldColumn = { bg = "#0a1520" },
    Folded = { bg = "#102030" },

    Comment = { fg = "#546e7a", italic = true },
    Keyword = { fg = "#90caf9" },
    Statement = { fg = "#90caf9" },
    Conditional = { fg = "#90caf9" },
    Repeat = { fg = "#90caf9" },
    Label = { fg = "#90caf9" },

    String = { fg = "#b3e5fc" },
    Character = { fg = "#b3e5fc" },

    Number = { fg = "#29b6f6" },
    Float = { fg = "#29b6f6" },
    Boolean = { fg = "#29b6f6" },

    Function = { fg = "#42a5f5" },

    Identifier = { fg = "#b0c4de" },

    Type = { fg = "#90caf9" },
    Structure = { fg = "#90caf9" },
    Typedef = { fg = "#90caf9" },

    Constant = { fg = "#29b6f6" },
    Define = { fg = "#90caf9" },
    Macro = { fg = "#90caf9" },
    PreCondit = { fg = "#90caf9" },
    PreProc = { fg = "#90caf9" },
    Include = { fg = "#90caf9" },

    Operator = { fg = "#90caf9" },
    Delimiter = { fg = "#546e7a" },

    Tag = { fg = "#42a5f5" },
    Attribute = { fg = "#90caf9" },

    Class = { fg = "#29b6f6" },
    Interface = { fg = "#90caf9" },
    Enum = { fg = "#b3e5fc" },
    EnumMember = { fg = "#b3e5fc" },

    Parameter = { fg = "#b0c4de" },
    Property = { fg = "#90caf9" },

    Builtin = { fg = "#90caf9" },

    Special = { fg = "#29b6f6" },
    SpecialChar = { fg = "#29b6f6" },
    SpecialKey = { fg = "#0d1b2a" },

    Error = { fg = "#ef5350" },
    WarningMsg = { fg = "#ffa726" },
    InfoMsg = { fg = "#26c6da" },
    MoreMsg = { fg = "#66bb6a" },

    Todo = { fg = "#29b6f6", bold = true },
    Search = { fg = "#0a1520", bg = "#29b6f6" },
    IncSearch = { fg = "#0a1520", bg = "#29b6f6" },

    Pmenu = { fg = "#b0c4de", bg = "#0a141e" },
    PmenuSel = { fg = "#b0c4de", bg = "#1565c0" },
    PmenuSbar = { bg = "#09131d" },
    PmenuThumb = { bg = "#546e7a" },

    StatusLine = { fg = "#b0c4de", bg = "#09131d" },
    StatusLineNC = { fg = "#546e7a", bg = "#09131d" },
    WinSeparator = { fg = "#0b1723" },

    TabLine = { bg = "#0a141e" },
    TabLineFill = { bg = "#0a141e" },
    TabLineSel = { fg = "#b0c4de", bg = "#0a1520" },

    Title = { fg = "#42a5f5", bold = true },
    Directory = { fg = "#42a5f5" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#ef5350" },
    HealthWarning = { fg = "#ffa726" },
    HealthSuccess = { fg = "#66bb6a" },

    DiagnosticError = { fg = "#ef5350" },
    DiagnosticWarn = { fg = "#ffa726" },
    DiagnosticInfo = { fg = "#26c6da" },
    DiagnosticHint = { fg = "#66bb6a" },

    DiffAdd = { bg = "#47834a" },
    DiffDelete = { bg = "#a73a38" },
    DiffChange = { bg = "#1b8b99" },
    DiffText = { bg = "#1e9eae" },

    GitSignsAdd = { fg = "#66bb6a" },
    GitSignsChange = { fg = "#26c6da" },
    GitSignsDelete = { fg = "#ef5350" },
  },
}

return theme