-- Invoker theme for Neovim
-- Generated by dota-themes
-- The Grand Magus — Quas conjures ice, Wex commands storm, Exort wields fire. Cold Snap freezes, Ghost Walk vanishes, Tornado lifts, E.M.P. detonates, Sun Strike burns from the sky, Chaos Meteor scorches the earth

vim.api.nvim_command("highlight clear")
vim.g.colors_name = "dota-invoker"
vim.opt.background = "dark"

local hl = vim.api.nvim_set_hl

-- Base
vim.api.nvim_set_hl(0, "Normal", { fg = "#c8c0e0", bg = "#0c0e1a" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#c8c0e0", bg = "#0c0e1a" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#c8c0e0", bg = "#0c0e1a" })

-- Cursor
vim.api.nvim_set_hl(0, "Cursor", { fg = "#0c0e1a", bg = "#d07828" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#12142a" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#12142a" })

-- Selection
vim.api.nvim_set_hl(0, "Visual", { bg = "#282050" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#282050" })

-- Line numbers
vim.api.nvim_set_hl(0, "LineNr", { fg = "#101222" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#d07828" })

-- Signs & Folds
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0c0e1a" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#0c0e1a" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#12142a" })

-- Syntax
vim.api.nvim_set_hl(0, "Comment", { fg = "#5a5878", italic = true })

vim.api.nvim_set_hl(0, "Keyword", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Label", { fg = "#9868d0" })

vim.api.nvim_set_hl(0, "String", { fg = "#d8a030" })
vim.api.nvim_set_hl(0, "Character", { fg = "#d8a030" })

vim.api.nvim_set_hl(0, "Number", { fg = "#d07828" })
vim.api.nvim_set_hl(0, "Float", { fg = "#d07828" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#d07828" })

vim.api.nvim_set_hl(0, "Function", { fg = "#e89040" })

vim.api.nvim_set_hl(0, "Identifier", { fg = "#c8c0e0" })

vim.api.nvim_set_hl(0, "Type", { fg = "#48b8d0" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#48b8d0" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#48b8d0" })

vim.api.nvim_set_hl(0, "Constant", { fg = "#d07828" })
vim.api.nvim_set_hl(0, "Define", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Include", { fg = "#9868d0" })

vim.api.nvim_set_hl(0, "Operator", { fg = "#5a5878" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#5a5878" })

vim.api.nvim_set_hl(0, "Tag", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Attribute", { fg = "#48b8d0" })

vim.api.nvim_set_hl(0, "Class", { fg = "#48b8d0" })
vim.api.nvim_set_hl(0, "Interface", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "Enum", { fg = "#d07828" })
vim.api.nvim_set_hl(0, "EnumMember", { fg = "#d07828" })

vim.api.nvim_set_hl(0, "Parameter", { fg = "#a098c0" })
vim.api.nvim_set_hl(0, "Property", { fg = "#7898c0" })

vim.api.nvim_set_hl(0, "Builtin", { fg = "#9868d0" })

vim.api.nvim_set_hl(0, "Special", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#101222" })

-- Diagnostics
vim.api.nvim_set_hl(0, "Error", { fg = "#d05040" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#d8a030" })
vim.api.nvim_set_hl(0, "InfoMsg", { fg = "#48b8d0" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#d07828" })

vim.api.nvim_set_hl(0, "Todo", { fg = "#9868d0", bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = "#0c0e1a", bg = "#9868d0" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0c0e1a", bg = "#d07828" })

-- Completion menu
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#c8c0e0", bg = "#0b0d19" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#c8c0e0", bg = "#282050" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#0b0d18" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#5a5878" })

-- Statusline
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#c8c0e0", bg = "#0b0d18" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#5a5878", bg = "#0b0d18" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#0d0f1c" })

-- Tabs
vim.api.nvim_set_hl(0, "TabLine", { bg = "#0b0d19" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0b0d19" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#c8c0e0", bg = "#0c0e1a" })

-- Misc
vim.api.nvim_set_hl(0, "Title", { fg = "#d07828", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#d07828" })

hl(0, "Underlined", { underline = true })
hl(0, "Bold", { bold = true })
hl(0, "Italic", { italic = true })

-- Health
vim.api.nvim_set_hl(0, "HealthError", { fg = "#d05040" })
vim.api.nvim_set_hl(0, "HealthWarning", { fg = "#d8a030" })
vim.api.nvim_set_hl(0, "HealthSuccess", { fg = "#d07828" })

-- Diagnostic
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#d05040" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#d8a030" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#48b8d0" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#d07828" })

vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#d05040", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#d8a030", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#48b8d0", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#d07828", undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#92541c" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#92382d" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#328192" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#3a93a6" })

-- Git signs
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#d07828" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#48b8d0" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#d05040" })

-- Telescope
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#5a5878" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#c8c0e0", bg = "#282050" })

-- NvimTree
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#282050" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = "#c8c0e0", bg = "#0c0e1a" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#12142a" })

-- WhichKey
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#9868d0" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#d07828" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#c8c0e0" })

-- Lazy
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#0b0d19" })
vim.api.nvim_set_hl(0, "LazyButtonActive", { bg = "#282050" })
vim.api.nvim_set_hl(0, "LazyComment", { fg = "#5a5878" })