-- Necrophos theme for Neovim
-- Generated by dota-themes
-- The Radiant Reaper — a sickly green death priest who drains life from the living

local theme_name = "dota-necrophos"

local theme = {
  colors = {
    base = "#0f191f",
    mantle = "#0e181d",
    surface0 = "#0f1a20",
    surface1 = "#101b21",
    surface2 = "#101b22",
    overlay0 = "#66736D",
    overlay1 = "#142630",
    overlay2 = "#1a2620",
    text = "#D7E5DD",
    subtext0 = "#b7c3bc",
    subtext1 = "#c6d3cb",
    primary = "#54C892",
    secondary = "#6EE7A8",
    accent = "#78D6AE",
    error = "#c25c5c",
    warning = "#C9A45A",
    info = "#69C7B5",
    success = "#6EE7A8",
    cursor = "#6EE7A8",
    selection = "#1d534d",
    lineHighlight = "#142630",
    gutter = "#142630",
  },
  highlights = {
    Normal = { fg = "#D7E5DD", bg = "#0f191f" },
    NormalFloat = { fg = "#D7E5DD", bg = "#0f191f" },
    NormalNC = { fg = "#D7E5DD", bg = "#0f191f" },

    Cursor = { fg = "#0f191f", bg = "#6EE7A8" },
    CursorLine = { bg = "#142630" },
    CursorColumn = { bg = "#142630" },

    Visual = { bg = "#1d534d" },
    VisualNOS = { bg = "#1d534d" },

    LineNr = { fg = "#142630" },
    CursorLineNr = { fg = "#6EE7A8" },

    SignColumn = { bg = "#0f191f" },
    FoldColumn = { bg = "#0f191f" },
    Folded = { bg = "#142630" },

    Comment = { fg = "#66736D", italic = true },
    Keyword = { fg = "#8c7ac2" },
    Statement = { fg = "#8c7ac2" },
    Conditional = { fg = "#8c7ac2" },
    Repeat = { fg = "#8c7ac2" },
    Label = { fg = "#8c7ac2" },

    String = { fg = "#C9A45A" },
    Character = { fg = "#C9A45A" },

    Number = { fg = "#AF8B43" },
    Float = { fg = "#AF8B43" },
    Boolean = { fg = "#AF8B43" },

    Function = { fg = "#6E9440" },

    Identifier = { fg = "#D7E5DD" },

    Type = { fg = "#69C7B5" },
    Structure = { fg = "#69C7B5" },
    Typedef = { fg = "#69C7B5" },

    Constant = { fg = "#AF8B43" },
    Define = { fg = "#8c7ac2" },
    Macro = { fg = "#8c7ac2" },
    PreCondit = { fg = "#8c7ac2" },
    PreProc = { fg = "#8c7ac2" },
    Include = { fg = "#8c7ac2" },

    Operator = { fg = "#66736D" },
    Delimiter = { fg = "#66736D" },

    Tag = { fg = "#6EE7A8" },
    Attribute = { fg = "#69C7B5" },

    Class = { fg = "#69C7B5" },
    Interface = { fg = "#69C7B5" },
    Enum = { fg = "#AF8B43" },
    EnumMember = { fg = "#AF8B43" },

    Parameter = { fg = "#B6D2C8" },
    Property = { fg = "#A4E2D0" },

    Builtin = { fg = "#6EE7A8" },

    Special = { fg = "#78D6AE" },
    SpecialChar = { fg = "#78D6AE" },
    SpecialKey = { fg = "#142630" },

    Error = { fg = "#c25c5c" },
    WarningMsg = { fg = "#C9A45A" },
    InfoMsg = { fg = "#69C7B5" },
    MoreMsg = { fg = "#6EE7A8" },

    Todo = { fg = "#78D6AE", bold = true },
    Search = { fg = "#0f191f", bg = "#78D6AE" },
    IncSearch = { fg = "#0f191f", bg = "#6EE7A8" },

    Pmenu = { fg = "#D7E5DD", bg = "#0e181d" },
    PmenuSel = { fg = "#D7E5DD", bg = "#1d534d" },
    PmenuSbar = { bg = "#0e171d" },
    PmenuThumb = { bg = "#66736D" },

    StatusLine = { fg = "#D7E5DD", bg = "#0e171d" },
    StatusLineNC = { fg = "#66736D", bg = "#0e171d" },
    WinSeparator = { fg = "#101b21" },

    TabLine = { bg = "#0e181d" },
    TabLineFill = { bg = "#0e181d" },
    TabLineSel = { fg = "#D7E5DD", bg = "#0f191f" },

    Title = { fg = "#54C892", bold = true },
    Directory = { fg = "#54C892" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#c25c5c" },
    HealthWarning = { fg = "#C9A45A" },
    HealthSuccess = { fg = "#6EE7A8" },

    DiagnosticError = { fg = "#c25c5c" },
    DiagnosticWarn = { fg = "#C9A45A" },
    DiagnosticInfo = { fg = "#69C7B5" },
    DiagnosticHint = { fg = "#6EE7A8" },

    DiffAdd = { bg = "#4da276" },
    DiffDelete = { bg = "#884040" },
    DiffChange = { bg = "#4a8b7f" },
    DiffText = { bg = "#549f91" },

    GitSignsAdd = { fg = "#6EE7A8" },
    GitSignsChange = { fg = "#69C7B5" },
    GitSignsDelete = { fg = "#c25c5c" },
  },
}

return theme