-- Necrophos theme for Neovim
-- Generated by dota-themes
-- The Radiant Reaper — a sickly green death priest who drains life from the living

local theme_name = "dota-necrophos"

local theme = {
  colors = {
    base = "#0a1a0f",
    mantle = "#0a190e",
    surface0 = "#0a1b0f",
    surface1 = "#0b1c10",
    surface2 = "#0b1c10",
    overlay0 = "#5a7a5e",
    overlay1 = "#0d2213",
    overlay2 = "#1b3a1e",
    text = "#c8e6c9",
    subtext0 = "#aac4ab",
    subtext1 = "#b8d4b9",
    primary = "#4caf50",
    secondary = "#81c784",
    accent = "#00e676",
    error = "#ef5350",
    warning = "#ffb74d",
    info = "#4dd0e1",
    success = "#66bb6a",
    cursor = "#00e676",
    selection = "#1b5e20",
    lineHighlight = "#0f2915",
    gutter = "#0d2213",
  },
  highlights = {
    Normal = { fg = "#c8e6c9", bg = "#0a1a0f" },
    NormalFloat = { fg = "#c8e6c9", bg = "#0a1a0f" },
    NormalNC = { fg = "#c8e6c9", bg = "#0a1a0f" },

    Cursor = { fg = "#0a1a0f", bg = "#00e676" },
    CursorLine = { bg = "#0f2915" },
    CursorColumn = { bg = "#0f2915" },

    Visual = { bg = "#1b5e20" },
    VisualNOS = { bg = "#1b5e20" },

    LineNr = { fg = "#0d2213" },
    CursorLineNr = { fg = "#00e676" },

    SignColumn = { bg = "#0a1a0f" },
    FoldColumn = { bg = "#0a1a0f" },
    Folded = { bg = "#0f2915" },

    Comment = { fg = "#5a7a5e", italic = true },
    Keyword = { fg = "#66bb6a" },
    Statement = { fg = "#66bb6a" },
    Conditional = { fg = "#66bb6a" },
    Repeat = { fg = "#66bb6a" },
    Label = { fg = "#66bb6a" },

    String = { fg = "#a5d6a7" },
    Character = { fg = "#a5d6a7" },

    Number = { fg = "#00e676" },
    Float = { fg = "#00e676" },
    Boolean = { fg = "#00e676" },

    Function = { fg = "#4caf50" },

    Identifier = { fg = "#c8e6c9" },

    Type = { fg = "#81c784" },
    Structure = { fg = "#81c784" },
    Typedef = { fg = "#81c784" },

    Constant = { fg = "#00e676" },
    Define = { fg = "#66bb6a" },
    Macro = { fg = "#66bb6a" },
    PreCondit = { fg = "#66bb6a" },
    PreProc = { fg = "#66bb6a" },
    Include = { fg = "#66bb6a" },

    Operator = { fg = "#66bb6a" },
    Delimiter = { fg = "#5a7a5e" },

    Tag = { fg = "#4caf50" },
    Attribute = { fg = "#81c784" },

    Class = { fg = "#00e676" },
    Interface = { fg = "#81c784" },
    Enum = { fg = "#a5d6a7" },
    EnumMember = { fg = "#a5d6a7" },

    Parameter = { fg = "#c8e6c9" },
    Property = { fg = "#81c784" },

    Builtin = { fg = "#66bb6a" },

    Special = { fg = "#00e676" },
    SpecialChar = { fg = "#00e676" },
    SpecialKey = { fg = "#0d2213" },

    Error = { fg = "#ef5350" },
    WarningMsg = { fg = "#ffb74d" },
    InfoMsg = { fg = "#4dd0e1" },
    MoreMsg = { fg = "#66bb6a" },

    Todo = { fg = "#00e676", bold = true },
    Search = { fg = "#0a1a0f", bg = "#00e676" },
    IncSearch = { fg = "#0a1a0f", bg = "#00e676" },

    Pmenu = { fg = "#c8e6c9", bg = "#0a190e" },
    PmenuSel = { fg = "#c8e6c9", bg = "#1b5e20" },
    PmenuSbar = { bg = "#09180e" },
    PmenuThumb = { bg = "#5a7a5e" },

    StatusLine = { fg = "#c8e6c9", bg = "#09180e" },
    StatusLineNC = { fg = "#5a7a5e", bg = "#09180e" },
    WinSeparator = { fg = "#0b1c10" },

    TabLine = { bg = "#0a190e" },
    TabLineFill = { bg = "#0a190e" },
    TabLineSel = { fg = "#c8e6c9", bg = "#0a1a0f" },

    Title = { fg = "#4caf50", bold = true },
    Directory = { fg = "#4caf50" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#ef5350" },
    HealthWarning = { fg = "#ffb74d" },
    HealthSuccess = { fg = "#66bb6a" },

    DiagnosticError = { fg = "#ef5350" },
    DiagnosticWarn = { fg = "#ffb74d" },
    DiagnosticInfo = { fg = "#4dd0e1" },
    DiagnosticHint = { fg = "#66bb6a" },

    DiffAdd = { bg = "#47834a" },
    DiffDelete = { bg = "#a73a38" },
    DiffChange = { bg = "#36929e" },
    DiffText = { bg = "#3ea6b4" },

    GitSignsAdd = { fg = "#66bb6a" },
    GitSignsChange = { fg = "#4dd0e1" },
    GitSignsDelete = { fg = "#ef5350" },
  },
}

return theme