-- Brewmaster theme for Neovim
-- Generated by dota-themes
-- The Grandmaster — celestial pandaren warrior who commands the three elemental brews

local theme_name = "dota-brewmaster"

local theme = {
  colors = {
    base = "#1a1008",
    mantle = "#190f08",
    surface0 = "#1b1008",
    surface1 = "#1c1108",
    surface2 = "#1c1109",
    overlay0 = "#8a7a5a",
    overlay1 = "#201408",
    overlay2 = "#2a2010",
    text = "#e0c8a0",
    subtext0 = "#beaa88",
    subtext1 = "#ceb893",
    primary = "#ff8f00",
    secondary = "#ffb74d",
    accent = "#ffd54f",
    error = "#ef5350",
    warning = "#ffab40",
    info = "#4fc3f7",
    success = "#81c784",
    cursor = "#ffd54f",
    selection = "#e65100",
    lineHighlight = "#281a0c",
    gutter = "#201408",
  },
  highlights = {
    Normal = { fg = "#e0c8a0", bg = "#1a1008" },
    NormalFloat = { fg = "#e0c8a0", bg = "#1a1008" },
    NormalNC = { fg = "#e0c8a0", bg = "#1a1008" },

    Cursor = { fg = "#1a1008", bg = "#ffd54f" },
    CursorLine = { bg = "#281a0c" },
    CursorColumn = { bg = "#281a0c" },

    Visual = { bg = "#e65100" },
    VisualNOS = { bg = "#e65100" },

    LineNr = { fg = "#201408" },
    CursorLineNr = { fg = "#ffd54f" },

    SignColumn = { bg = "#1a1008" },
    FoldColumn = { bg = "#1a1008" },
    Folded = { bg = "#281a0c" },

    Comment = { fg = "#8a7a5a", italic = true },
    Keyword = { fg = "#ffb74d" },
    Statement = { fg = "#ffb74d" },
    Conditional = { fg = "#ffb74d" },
    Repeat = { fg = "#ffb74d" },
    Label = { fg = "#ffb74d" },

    String = { fg = "#ffe0b2" },
    Character = { fg = "#ffe0b2" },

    Number = { fg = "#ffd54f" },
    Float = { fg = "#ffd54f" },
    Boolean = { fg = "#ffd54f" },

    Function = { fg = "#ff8f00" },

    Identifier = { fg = "#e0c8a0" },

    Type = { fg = "#ffb74d" },
    Structure = { fg = "#ffb74d" },
    Typedef = { fg = "#ffb74d" },

    Constant = { fg = "#ffd54f" },
    Define = { fg = "#ffb74d" },
    Macro = { fg = "#ffb74d" },
    PreCondit = { fg = "#ffb74d" },
    PreProc = { fg = "#ffb74d" },
    Include = { fg = "#ffb74d" },

    Operator = { fg = "#ffb74d" },
    Delimiter = { fg = "#8a7a5a" },

    Tag = { fg = "#ff8f00" },
    Attribute = { fg = "#ffb74d" },

    Class = { fg = "#ffd54f" },
    Interface = { fg = "#ffb74d" },
    Enum = { fg = "#ffe0b2" },
    EnumMember = { fg = "#ffe0b2" },

    Parameter = { fg = "#e0c8a0" },
    Property = { fg = "#ffb74d" },

    Builtin = { fg = "#ffb74d" },

    Special = { fg = "#ffd54f" },
    SpecialChar = { fg = "#ffd54f" },
    SpecialKey = { fg = "#201408" },

    Error = { fg = "#ef5350" },
    WarningMsg = { fg = "#ffab40" },
    InfoMsg = { fg = "#4fc3f7" },
    MoreMsg = { fg = "#81c784" },

    Todo = { fg = "#ffd54f", bold = true },
    Search = { fg = "#1a1008", bg = "#ffd54f" },
    IncSearch = { fg = "#1a1008", bg = "#ffd54f" },

    Pmenu = { fg = "#e0c8a0", bg = "#190f08" },
    PmenuSel = { fg = "#e0c8a0", bg = "#e65100" },
    PmenuSbar = { bg = "#180f07" },
    PmenuThumb = { bg = "#8a7a5a" },

    StatusLine = { fg = "#e0c8a0", bg = "#180f07" },
    StatusLineNC = { fg = "#8a7a5a", bg = "#180f07" },
    WinSeparator = { fg = "#1c1109" },

    TabLine = { bg = "#190f08" },
    TabLineFill = { bg = "#190f08" },
    TabLineSel = { fg = "#e0c8a0", bg = "#1a1008" },

    Title = { fg = "#ff8f00", bold = true },
    Directory = { fg = "#ff8f00" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#ef5350" },
    HealthWarning = { fg = "#ffab40" },
    HealthSuccess = { fg = "#81c784" },

    DiagnosticError = { fg = "#ef5350" },
    DiagnosticWarn = { fg = "#ffab40" },
    DiagnosticInfo = { fg = "#4fc3f7" },
    DiagnosticHint = { fg = "#81c784" },

    DiffAdd = { bg = "#5a8b5c" },
    DiffDelete = { bg = "#a73a38" },
    DiffChange = { bg = "#3789ad" },
    DiffText = { bg = "#3f9cc6" },

    GitSignsAdd = { fg = "#81c784" },
    GitSignsChange = { fg = "#4fc3f7" },
    GitSignsDelete = { fg = "#ef5350" },
  },
}

return theme