-- Lich theme for Neovim
-- Generated by dota-themes
-- The Frost Mage — ancient frost sorcerer, lord of the frozen wastes

local theme_name = "dota-lich"

local theme = {
  colors = {
    base = "#0a1218",
    mantle = "#0a1117",
    surface0 = "#0a1319",
    surface1 = "#0b1319",
    surface2 = "#0b141a",
    overlay0 = "#4a6a7a",
    overlay1 = "#0d1820",
    overlay2 = "#1a2a35",
    text = "#b8d4e3",
    subtext0 = "#9cb4c1",
    subtext1 = "#a9c3d1",
    primary = "#4fc3f7",
    secondary = "#81d4fa",
    accent = "#29b6f6",
    error = "#ef5350",
    warning = "#ffb74d",
    info = "#4dd0e1",
    success = "#81c784",
    cursor = "#29b6f6",
    selection = "#0d47a1",
    lineHighlight = "#101e28",
    gutter = "#0d1820",
  },
  highlights = {
    Normal = { fg = "#b8d4e3", bg = "#0a1218" },
    NormalFloat = { fg = "#b8d4e3", bg = "#0a1218" },
    NormalNC = { fg = "#b8d4e3", bg = "#0a1218" },

    Cursor = { fg = "#0a1218", bg = "#29b6f6" },
    CursorLine = { bg = "#101e28" },
    CursorColumn = { bg = "#101e28" },

    Visual = { bg = "#0d47a1" },
    VisualNOS = { bg = "#0d47a1" },

    LineNr = { fg = "#0d1820" },
    CursorLineNr = { fg = "#29b6f6" },

    SignColumn = { bg = "#0a1218" },
    FoldColumn = { bg = "#0a1218" },
    Folded = { bg = "#101e28" },

    Comment = { fg = "#4a6a7a", italic = true },
    Keyword = { fg = "#81d4fa" },
    Statement = { fg = "#81d4fa" },
    Conditional = { fg = "#81d4fa" },
    Repeat = { fg = "#81d4fa" },
    Label = { fg = "#81d4fa" },

    String = { fg = "#b3e5fc" },
    Character = { fg = "#b3e5fc" },

    Number = { fg = "#29b6f6" },
    Float = { fg = "#29b6f6" },
    Boolean = { fg = "#29b6f6" },

    Function = { fg = "#4fc3f7" },

    Identifier = { fg = "#b8d4e3" },

    Type = { fg = "#81d4fa" },
    Structure = { fg = "#81d4fa" },
    Typedef = { fg = "#81d4fa" },

    Constant = { fg = "#29b6f6" },
    Define = { fg = "#81d4fa" },
    Macro = { fg = "#81d4fa" },
    PreCondit = { fg = "#81d4fa" },
    PreProc = { fg = "#81d4fa" },
    Include = { fg = "#81d4fa" },

    Operator = { fg = "#81d4fa" },
    Delimiter = { fg = "#4a6a7a" },

    Tag = { fg = "#4fc3f7" },
    Attribute = { fg = "#81d4fa" },

    Class = { fg = "#29b6f6" },
    Interface = { fg = "#81d4fa" },
    Enum = { fg = "#b3e5fc" },
    EnumMember = { fg = "#b3e5fc" },

    Parameter = { fg = "#b8d4e3" },
    Property = { fg = "#81d4fa" },

    Builtin = { fg = "#81d4fa" },

    Special = { fg = "#29b6f6" },
    SpecialChar = { fg = "#29b6f6" },
    SpecialKey = { fg = "#0d1820" },

    Error = { fg = "#ef5350" },
    WarningMsg = { fg = "#ffb74d" },
    InfoMsg = { fg = "#4dd0e1" },
    MoreMsg = { fg = "#81c784" },

    Todo = { fg = "#29b6f6", bold = true },
    Search = { fg = "#0a1218", bg = "#29b6f6" },
    IncSearch = { fg = "#0a1218", bg = "#29b6f6" },

    Pmenu = { fg = "#b8d4e3", bg = "#0a1117" },
    PmenuSel = { fg = "#b8d4e3", bg = "#0d47a1" },
    PmenuSbar = { bg = "#091116" },
    PmenuThumb = { bg = "#4a6a7a" },

    StatusLine = { fg = "#b8d4e3", bg = "#091116" },
    StatusLineNC = { fg = "#4a6a7a", bg = "#091116" },
    WinSeparator = { fg = "#0b131a" },

    TabLine = { bg = "#0a1117" },
    TabLineFill = { bg = "#0a1117" },
    TabLineSel = { fg = "#b8d4e3", bg = "#0a1218" },

    Title = { fg = "#4fc3f7", bold = true },
    Directory = { fg = "#4fc3f7" },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    HealthError = { fg = "#ef5350" },
    HealthWarning = { fg = "#ffb74d" },
    HealthSuccess = { fg = "#81c784" },

    DiagnosticError = { fg = "#ef5350" },
    DiagnosticWarn = { fg = "#ffb74d" },
    DiagnosticInfo = { fg = "#4dd0e1" },
    DiagnosticHint = { fg = "#81c784" },

    DiffAdd = { bg = "#5a8b5c" },
    DiffDelete = { bg = "#a73a38" },
    DiffChange = { bg = "#36929e" },
    DiffText = { bg = "#3ea6b4" },

    GitSignsAdd = { fg = "#81c784" },
    GitSignsChange = { fg = "#4dd0e1" },
    GitSignsDelete = { fg = "#ef5350" },
  },
}

return theme