import type {
  GeneratedFile,
  GeneratorOptions,
  PlatformGenerator,
} from "@dota-themes/generator-core";
import type { HeroPalette } from "@dota-themes/palettes";

function generateWezToml(palette: HeroPalette): string {
  const t = palette.terminal;
  const name = palette.metadata.title;

  return `# ${name} theme for WezTerm
# Generated by dota-themes
# ${palette.metadata.description}

[colors]
foreground = "${t.foreground}"
background = "${t.background}"
cursor_fg = "${t.background}"
cursor_bg = "${t.cursor}"
cursor_border = "${t.cursor}"
selection_fg = "${t.foreground}"
selection_bg = "${t.selectionBackground}"

[colors.ansi]
"${t.black}"
"${t.red}"
"${t.green}"
"${t.yellow}"
"${t.blue}"
"${t.magenta}"
"${t.cyan}"
"${t.white}"

[colors.brights]
"${t.brightBlack}"
"${t.brightRed}"
"${t.brightGreen}"
"${t.brightYellow}"
"${t.brightBlue}"
"${t.brightMagenta}"
"${t.brightCyan}"
"${t.brightWhite}"

[metadata]
name = "Dota ${name}"
author = "dota-themes"
`;
}

export const weztermGenerator: PlatformGenerator = {
  name: "wezterm",
  fileExtension: "toml",

  generate(options: GeneratorOptions): GeneratedFile[] {
    const content = generateWezToml(options.hero);
    const fileName = `dota-${options.hero.hero}.toml`;
    return [{ path: `${options.outputDir}/${fileName}`, content }];
  },
};
